---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_pip: true
  require_ansible_repo: false
  ansible_version:  2.3.0.0
  ansible_verbose:  false
  ansible_verbosity: 2
  ansible_diff: true
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>

platforms:
  - name: ubuntu-14.04
    driver:
      box: bento/ubuntu-14.04
  - name: centos-7.2
    driver:
      box: bento/centos-7.2

suites:
  - name: server01
    driver:
      network:
        - ["private_network", { ip: "172.29.129.181" }]
  - name: server02
    driver:
      network:
        - ["private_network", { ip: "172.29.129.182" }]
  - name: server03
    driver:
      network:
        - ["private_network", { ip: "172.29.129.183" }]
  - name: client
    driver:
      network:
        - ["private_network", { ip: "172.29.129.184" }]
